# Shock mode, one of; random, last_hit_percentage
shock_mode = "random"
# Minimum duration of the shock
min_duration = 1
# Maximum duration of the shock
max_duration = 1
# Minimum intensity of the shock, 1-100
min_intensity = 1
# Maximum intensity of the shock, 1-100
max_intensity = 1
# Beep when match starts
beep_on_match_start = false
# Beep when round starts
beep_on_round_start = false
# PiShock username to access the api
username = ""
# PiShock share code to access the api
code = ""
# PiShock api key to access the api
apikey = ""